### ISSUE TITLE
the as: option in the example does nothing.  Example is poor.

### ISSUE THREAD

**Issue by gb23** [learn-co-curriculum/rails-url-helpers-readme#16]
get '/register', to: 'users#new' 
 is the same thing as 
get '/register', to: 'users#new', as: 'register'
So why even add the as: 'register' to this route?
Putting this in a section of the lesson USING THE :AS OPTION isn't a good idea.  Students are looking for how the as: option works.  I guess you could keep the example, but change the section to USING THE :AS OPTION NONSENSICALLY. ;)

A better example would be 
get ‘/users/new’,  to: ‘users#new’, as: ‘register’
because now, we are changing the URL helper method from  users_new_path to register_path and the the as: option actually serves a purpose here

**Comment by cjbrock** [comment]
You're absolutely right, and reading through the narrative above the code snippet, I think that was the original intent of the example. I'm pretty sure the code example was just written incorrectly. We're currently working on a major rewrite of the Rails section but for now, I'm just going to track this in a known issue. I'll come back and tag it in an comment when I have it written.

**Comment by cjbrock** [comment]
You can track the new issue [here](https://github.com/learn-co-curriculum/rails-url-helpers-readme/issues/19)

Thank you!
// Corinna
