### ISSUE TITLE
Known Issue: rewrite :as section

### ISSUE THREAD

**Issue by cjbrock** [learn-co-curriculum/rails-url-helpers-readme#19]
The :as section is not written as a good example for students. The example given is unclear as to why it benefits the developer to go that route. Saying
`get '/register', to: 'users#new', as: 'register'`
is just the same as saying
`get '/register', to: 'users#new'`

A better example would be 
`get ‘/users/new’, to: ‘users#new’, as: ‘register’`.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
