### ISSUE TITLE
Switched from Posts model to Users model for the as: example

### ISSUE THREAD

**Issue by SwellPF** [learn-co-curriculum/rails-url-helpers-readme#21]
For the "Using the :as option" section at the bottom of the lab, it reads as though you should add the suggested route to the routes.rb file but the problem is (unless I'm misunderstanding) that we don't even have a Users model or controller for this lab.  ???

Also, as someone had previously mentioned the example given for the :as option looks redundant.  Why would you use **get '/register', to: 'users#new', as: 'register'**?  That would behave the same as it does without the as: right?   Someone had suggested **get '/user/new', to: 'users#new', as: 'register'** which would make sense.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe this issue be resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
