### ISSUE TITLE
I found a typo on this lab

### ISSUE THREAD

**Issue by crayray** [learn-co-curriculum/rails-url-helpers-readme#31]
The grammar error is in  the first sentence:
"Since Rails is meant to be flexible. As a result, is there are typically a number of ways to accomplish the same goals."

I believe it's supposed to say:
"Rails is meant to be flexible and as a result there are typically many ways to accomplish the same goals."

**Comment by rrcobb** [comment]
Addressed in #33, thanks for reporting!
