### ISSUE TITLE
Need context of app in console for posts_path, posts_url, etc. to work

### ISSUE THREAD

**Issue by lisamarie616** [learn-co-curriculum/rails-url-helpers-readme#4]
The lesson says:

"If you open up the rails console in the sample app you can test these route helpers out. Run posts_path and see what the output is. You can also run posts_url and see how it prints out the full path instead of the relative path."

Running posts_path and posts_url wasn't working for me (I was getting this error: `NameError: undefined local variable or method 'posts' for main:Object`), but I found this on SO:

http://stackoverflow.com/questions/19217374/why-doesnt-posts-path-work-in-rails-console

Once I ran app.posts_path and app.posts_url it worked. I'm raising an issue rather than editing the lesson, because I'm not sure whether you want to explain why the context of app is needed (and if so, I wouldn't know how to explain that).

This part would also need editing:

"If you open up the rails console again you can call the route helpers. If you have a Post with an id of 3 you can run post_path(3)."

Thanks!

**Comment by AnnJohn** [comment]
thanks @lisamarie616, we will update this soon

**Comment by jmburges** [comment]
This is super wonky. You shouldn't need to do this app context stuff if you are using rails console. We should look into what's going on, because `app.posts_url` shouldn't be required.

**Comment by pletcher** [comment]
@jmburges Are you sure? I think by default `app` is required. (Unless there's something wonky with my install of Rails (which is possible, as I had to fight the Learn gem when configuring things).) I've tested on the linked example repo and on fresh repos -- all of them need `app`.

**Comment by scottcreynolds** [comment]
you do need `app` to use the route helpers, as seen here in the rails guide http://guides.rubyonrails.org/command_line.html#rails-console
